default: mysql
connections:
  mysql:
    driver: mysql+pymysql
    user: root
    password: "Guruji@XXXX"   # keep quoted
    host: 127.0.0.1
    port: 3306
    database: legacy_security_master
  postgres:
    driver: postgresql+psycopg       # psycopg v3
    user: postgres
    password: "Postgres@XXXX"
    host: 127.0.0.1
    port: 5432
    database: postgres

s3:
  bucket: security-recon-bucket
  prefix: results

logging:
  debug: true        # enable DEBUG everywhere
  level: INFO        # optional explicit level

exception_file:
  directory: ./resources/parquet
  filename: exceptions.<runid>.<yyyymmdd>.parquet